name: 'Backend Continuous Deployment' # Backend Continuous Deployment
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main


# jobs build test, lint =================================================
jobs:
  # lint job==========================================================
  lint-job:
    name: 'Lint Job'
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: |
          cd ./starter/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install pytest --dev
          pipenv install --dev
      
      - name: Run lint check
        run: cd ./starter/backend && pipenv run lint

  # Test job ===================================================================
  test-job:
    name: 'Test Job'
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: |
          cd ./starter/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install pytest --dev
          pipenv install --dev

      - name: Run tests
        run: |
          cd ./starter/backend 
          pipenv run test

  # Build lint job, Test job ==========================================================
  build:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Build Docker image
        run: |
          cd ./starter/backend
          docker build -t backend .
      
      - name: Tag Docker Image
        run: |
          cd ./starter/backend
          docker tag backend:latest 266956190511.dkr.ecr.us-west-2.amazonaws.com/backend:latest

      - name: Push Docker image to ECR
        run: |
          cd ./starter/backend
          docker push 266956190511.dkr.ecr.us-west-2.amazonaws.com/backend:latest
      
      - name: Kubeconfig Auth
        run: |
          aws eks update-kubeconfig --name hieu-prj4 --region us-west-2

      - name: Deploy to Kubernetes
        run: |
          cd ./starter/backend/k8s
          kustomize edit set image backend=266956190511.dkr.ecr.us-west-2.amazonaws.com/backend:latest
          kustomize build | kubectl apply -f -